"""add Department

Revision ID: 631cfbd4f168
Revises: 8ad819c64a8d
Create Date: 2024-06-28 13:28:46.062663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631cfbd4f168'
down_revision = '8ad819c64a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
