"""rename department

Revision ID: 938b01294a2c
Revises: 631cfbd4f168
Create Date: 2024-06-28 13:31:58.961235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938b01294a2c'
down_revision = '631cfbd4f168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###