"""add address column to departments

Revision ID: b28ddd87e90f
Revises: d55d2adb5d6f
Create Date: 2024-06-28 14:29:47.859717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28ddd87e90f'
down_revision = 'd55d2adb5d6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'address')
    # ### end Alembic commands ###
