"""rename address column

Revision ID: d55d2adb5d6f
Revises: 9cee90390755
Create Date: 2024-06-28 14:25:59.383008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd55d2adb5d6f'
down_revision = '9cee90390755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'address')
    # ### end Alembic commands ###
